# Generated by Django 2.1.2 on 2018-10-31 22:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateTimeField(blank=True, default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadesPorAno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDaAtividade', models.CharField(max_length=400)),
                ('local', models.CharField(max_length=1200)),
                ('descricao', models.TextField()),
                ('dataAtividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anoDaAtividade', to='sitenupeb.Ano')),
            ],
        ),
        migrations.CreateModel(
            name='CineDebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=600)),
                ('ano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anoDoEvento', to='sitenupeb.Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Exibicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DurationField(blank=True, default=datetime.timedelta)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=datetime.datetime.now)),
                ('titulo', models.CharField(max_length=400)),
                ('cinedebate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinedebate', to='sitenupeb.CineDebate')),
            ],
        ),
        migrations.CreateModel(
            name='FotosDasAtividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos-das-atividades')),
                ('comentario', models.CharField(blank=True, help_text='comentário o contexto da foto', max_length=1200)),
                ('atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotosDasAtividades', to='sitenupeb.AtividadesPorAno')),
            ],
        ),
        migrations.CreateModel(
            name='InformacoesTecnicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direcao', models.CharField(max_length=500)),
                ('ano', models.DateField(blank=True, default=datetime.datetime.now)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('duracao', models.DurationField(blank=True, default=datetime.timedelta)),
                ('filme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitenupeb.Filmes')),
            ],
        ),
        migrations.CreateModel(
            name='LinhasDePesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocalExibicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=250)),
                ('exibicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localExibicao', to='sitenupeb.Exibicao')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.TextField(help_text='descrição dos objetivos do grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ProximoFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filme', to='sitenupeb.Filmes')),
                ('sessao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao', to='sitenupeb.CineDebate')),
            ],
        ),
    ]
