# Generated by Django 2.1.2 on 2018-11-01 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ano',
            name='ano',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='atividadesporano',
            name='tituloDaAtividade',
            field=models.CharField(help_text='Título Atividade', max_length=400),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='cinedebate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinedebate', to='sitenupeb.CineDebate'),
        ),
    ]
