# Generated by Django 2.1.2 on 2018-11-01 00:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0002_auto_20181031_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicial', models.DateField(blank=True, default=datetime.datetime.now)),
                ('dataFinal', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ano',
            name='ano',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='atividadesporano',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodoDaAtividade', to='sitenupeb.Periodo'),
        ),
        migrations.AddField(
            model_name='cinedebate',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodoDosCineDebates', to='sitenupeb.Periodo'),
        ),
    ]
