# Generated by Django 2.1.2 on 2018-11-01 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0003_auto_20181031_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioExibicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DurationField(blank=True, default=datetime.timedelta)),
                ('filme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filmeAserExibido', to='sitenupeb.Filmes')),
            ],
        ),
        migrations.RemoveField(
            model_name='localexibicao',
            name='exibicao',
        ),
        migrations.AddField(
            model_name='localexibicao',
            name='horarioDaExibicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filmeExibido', to='sitenupeb.Filmes'),
        ),
        migrations.DeleteModel(
            name='Exibicao',
        ),
    ]
