# Generated by Django 2.1.2 on 2018-11-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0004_auto_20181031_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotosImagensDoCineDebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='imagens-cinedebate')),
                ('cinedebate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagensDoCineDebate', to='sitenupeb.CineDebate')),
            ],
        ),
    ]
