# Generated by Django 2.1.2 on 2018-11-01 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0005_fotosimagensdocinedebate'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadesporano',
            name='ano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anoDaAtividade', to='sitenupeb.Ano'),
        ),
        migrations.AddField(
            model_name='fotosimagensdocinedebate',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='atividadesporano',
            name='dataAtividade',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
