# Generated by Django 2.1.2 on 2018-11-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0006_auto_20181101_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadesporano',
            name='ano',
            field=models.ForeignKey(help_text='ano vigente da atividade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anoDaAtividade', to='sitenupeb.Ano'),
        ),
        migrations.AlterField(
            model_name='atividadesporano',
            name='periodo',
            field=models.ForeignKey(help_text='periodo vigente da atividade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodoDaAtividade', to='sitenupeb.Periodo'),
        ),
        migrations.AlterField(
            model_name='informacoestecnicas',
            name='filme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitenupeb.Filmes'),
        ),
    ]
