# Generated by Django 2.1.2 on 2018-11-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0009_horarioexibicao_localexibicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localexibicao',
            name='horarioDaExibicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filmeExibido', to='sitenupeb.Filmes'),
        ),
    ]
