# Generated by Django 2.1.2 on 2018-11-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0010_auto_20181101_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdasatividades',
            name='image',
            field=models.ImageField(upload_to='fotos-das-atividades/'),
        ),
    ]
