# Generated by Django 2.1.2 on 2018-11-01 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0011_auto_20181101_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localexibicao',
            name='horarioDaExibicao',
        ),
        migrations.AlterField(
            model_name='horarioexibicao',
            name='horario',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
