# Generated by Django 2.1.2 on 2018-11-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0012_auto_20181101_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframesLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkDoVideo', models.CharField(blank=True, max_length=3200, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventoDoLink', to='sitenupeb.EventosCineDebate')),
            ],
        ),
        migrations.AlterField(
            model_name='horarioexibicao',
            name='horario',
            field=models.TimeField(blank=True),
        ),
    ]
