# Generated by Django 2.1.2 on 2018-11-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0013_auto_20181102_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
