# Generated by Django 2.1.2 on 2018-11-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0016_auto_20181102_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscinedebate',
            name='cine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cineDebate', to='sitenupeb.CineDebate'),
            preserve_default=False,
        ),
    ]
