# Generated by Django 2.1.2 on 2018-11-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0017_eventoscinedebate_cine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='cine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cineDebate', to='sitenupeb.CineDebate'),
        ),
    ]
