# Generated by Django 2.1.2 on 2018-11-02 19:51

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0020_auto_20181102_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmes',
            options={'verbose_name': 'Filmes', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AddField(
            model_name='eventoscinedebate',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, help_text='This is a help text', null=True, verbose_name='My video'),
        ),
    ]
