# Generated by Django 2.1.2 on 2018-11-02 20:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0023_auto_20181102_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframeslinks',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, help_text='Geralmente é um trailer ou apresentação do vídeo', max_length=5000, null=True, verbose_name='Link do Video'),
        ),
    ]
