# Generated by Django 2.1.2 on 2018-11-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0024_auto_20181102_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iframeslinks',
            name='link',
        ),
        migrations.RemoveField(
            model_name='iframeslinks',
            name='linkDoVideo',
        ),
        migrations.AddField(
            model_name='eventoscinedebate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens-cinedebate'),
        ),
    ]
