# Generated by Django 2.1.2 on 2018-11-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0025_auto_20181102_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='titulo',
            field=models.CharField(blank=True, default='ainda não cadastrado', max_length=400, null=True),
        ),
    ]
