# Generated by Django 2.1.2 on 2018-11-02 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0026_auto_20181102_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='cine',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cineDebate', to='sitenupeb.CineDebate'),
        ),
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, help_text='data do evento', null=True),
        ),
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='endereco',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localExibicao', to='sitenupeb.LocalExibicao'),
        ),
        migrations.AlterField(
            model_name='eventoscinedebate',
            name='tituloDaExibicao',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
