# Generated by Django 2.1.2 on 2018-11-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0027_auto_20181102_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAmostrar', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Integrates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAmostrar', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAmostrar', models.CharField(max_length=300)),
                ('curriculo', models.URLField(blank=True, help_text='link do lattes', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='filmes',
            name='titulo',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
