# Generated by Django 2.1.2 on 2018-11-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0028_auto_20181104_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrates',
            new_name='Integrate',
        ),
    ]
