# Generated by Django 2.1.2 on 2018-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0030_auto_20181104_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhadepesquisa',
            name='teste',
            field=models.CharField(default='fasd', max_length=12),
            preserve_default=False,
        ),
    ]
