# Generated by Django 2.1.2 on 2018-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0031_linhadepesquisa_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linhadepesquisa',
            name='teste',
        ),
        migrations.AddField(
            model_name='linhadepesquisa',
            name='detalhes',
            field=models.TextField(blank=True, max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='linhadepesquisa',
            name='nomeDaLinha',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
