# Generated by Django 2.1.2 on 2018-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0032_auto_20181104_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhadepesquisa',
            name='nomeDaLinha',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Título da linha de pesquisa'),
        ),
    ]
