# Generated by Django 2.1.2 on 2018-11-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0033_auto_20181104_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosEstaduais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link do documento', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosInternacionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link do documento', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosNacionais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegislacaoEstadual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link do documento', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegislacaoNacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link do documento', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link da publicação', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link do sub-documento', null=True)),
                ('documentoPai', models.ForeignKey(blank=True, help_text='link do sub-documento', null=True, on_delete=django.db.models.deletion.CASCADE, to='sitenupeb.DocumentosNacionais')),
            ],
        ),
    ]
