# Generated by Django 2.1.2 on 2018-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0034_documentosestaduais_documentosinternacionais_documentosnacionais_legislacaoestadual_legislacaonacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentosestaduais',
            options={'verbose_name': 'DocumentosEstaduais', 'verbose_name_plural': 'Documentos Estaduais'},
        ),
        migrations.AlterModelOptions(
            name='documentosinternacionais',
            options={'verbose_name': 'DocumentosInternacionais', 'verbose_name_plural': 'Documentos Internacionais'},
        ),
        migrations.AlterModelOptions(
            name='documentosnacionais',
            options={'verbose_name': 'DocumentosNacionais', 'verbose_name_plural': 'Documentos Nacionais'},
        ),
        migrations.AlterModelOptions(
            name='eventoscinedebate',
            options={'verbose_name': 'EventosCineDebate', 'verbose_name_plural': 'Eventos CineDebate'},
        ),
        migrations.AlterModelOptions(
            name='fotosdasatividades',
            options={'verbose_name': 'FotosDasAtividades', 'verbose_name_plural': 'Fotos Das Atividades'},
        ),
        migrations.AlterModelOptions(
            name='legislacaoestadual',
            options={'verbose_name': 'LegislacaoEstadual', 'verbose_name_plural': 'Legislacao Estadual'},
        ),
        migrations.AlterModelOptions(
            name='legislacaonacional',
            options={'verbose_name': 'LegislacaoNacional', 'verbose_name_plural': 'Legislacao Nacional'},
        ),
        migrations.AddField(
            model_name='documentosnacionais',
            name='link',
            field=models.URLField(blank=True, help_text='link do sub-documento', null=True),
        ),
    ]
