# Generated by Django 2.1.2 on 2018-11-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0036_auto_20181108_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosevento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotosDoEvento', to='sitenupeb.Eventos'),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantesDoEvento', to='sitenupeb.Eventos'),
        ),
        migrations.AlterField(
            model_name='fotosevento',
            name='foto',
            field=models.ImageField(upload_to='fotos-dos-eventos/'),
        ),
    ]
