# Generated by Django 2.1.2 on 2018-11-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0037_auto_20181108_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateField(blank=True, help_text='data do evento', null=True),
        ),
    ]
