# Generated by Django 2.1.2 on 2018-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0038_auto_20181108_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='adicionais',
            field=models.TextField(blank=True, help_text='informações adicionais', null=True),
        ),
    ]
