# Generated by Django 2.1.2 on 2018-11-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0039_eventos_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='adicionais',
            field=models.TextField(blank=True, help_text='informações adicionais. Pode ser editado com html', null=True),
        ),
    ]
