# Generated by Django 2.1.2 on 2018-11-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0040_auto_20181109_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrate',
            new_name='Integrante',
        ),
    ]
