# Generated by Django 2.1.2 on 2018-11-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0041_auto_20181109_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmePorTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='titulo/descrição do filme', max_length=5000, null=True)),
                ('link', models.URLField(blank=True, help_text='link do filme', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, help_text='tema do filme', max_length=5000, null=True)),
            ],
        ),
    ]
