# Generated by Django 2.1.2 on 2018-11-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0042_filmeportema_tema'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tema',
            new_name='TemaFilme',
        ),
    ]
