# Generated by Django 2.1.2 on 2018-11-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0043_auto_20181109_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmeportema',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temaDofilme', to='sitenupeb.TemaFilme'),
        ),
    ]
