# Generated by Django 2.1.2 on 2018-11-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0044_filmeportema_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='temafilme',
            name='comentario',
            field=models.CharField(blank=True, help_text='comentário sobre o contexto', max_length=15000, null=True),
        ),
    ]
