# Generated by Django 2.1.2 on 2018-11-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0046_auto_20181109_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IframesLinks',
            new_name='VideoTrailer',
        ),
    ]
