# Generated by Django 2.1.2 on 2018-11-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0047_auto_20181109_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fotosImagensDoCineDebate',
            new_name='FotosDoCineDebate',
        ),
    ]
