# Generated by Django 2.1.2 on 2018-11-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0048_auto_20181109_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoMaterialDidatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, help_text='descrição e temas do material didático', max_length=5000, null=True)),
                ('link', models.URLField(blank=True, help_text='link do material didático', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDidatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='contexto do material didático', max_length=5000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='horarioexibicao',
            options={'verbose_name': 'Horário Exibicao', 'verbose_name_plural': 'Horários de Exibicao'},
        ),
        migrations.AlterModelOptions(
            name='informacoestecnicas',
            options={'verbose_name': 'Informações Técnicas', 'verbose_name_plural': 'Informações Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='leituraportema',
            options={'verbose_name': 'LeituraPorTema', 'verbose_name_plural': 'Leituras por Tema'},
        ),
        migrations.AlterModelOptions(
            name='linhadepesquisa',
            options={'verbose_name': 'Linha de Pesquisa', 'verbose_name_plural': 'Linhas de Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='objetivos',
            options={'verbose_name': 'Objetivos', 'verbose_name_plural': 'Objetivos'},
        ),
        migrations.AddField(
            model_name='descricaomaterialdidatico',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descricaoDoMaterialDidatico', to='sitenupeb.MaterialDidatico'),
        ),
    ]
