# Generated by Django 2.1.2 on 2018-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0049_auto_20181109_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisasEmAndamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='título da pesquisa', max_length=500, null=True)),
                ('aluno', models.CharField(blank=True, help_text='aluno da pesquisa', max_length=500, null=True)),
                ('modalidade', models.CharField(blank=True, help_text='tipo da pesquisa', max_length=500, null=True)),
                ('periodo', models.CharField(blank=True, help_text='periodo da pesquisa', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesquisasRealizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='título da pesquisa', max_length=500, null=True)),
                ('aluno', models.CharField(blank=True, help_text='aluno da pesquisa', max_length=500, null=True)),
                ('modalidade', models.CharField(blank=True, help_text='tipo da pesquisa', max_length=500, null=True)),
                ('periodo', models.CharField(blank=True, help_text='periodo da pesquisa', max_length=500, null=True)),
            ],
        ),
    ]
