# Generated by Django 2.1.2 on 2018-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0052_docentesppge_linha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppge',
            name='areadeconcentracao',
            field=models.CharField(blank=True, help_text='área de concentração', max_length=100, null=True),
        ),
    ]
