# Generated by Django 2.1.2 on 2018-11-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0053_ppge_areadeconcentracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoresPesq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='nome do pesquisador', max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link do currículo do pesquisador', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutorRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RefereciaCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='título da pesquisa', max_length=500, null=True)),
                ('link', models.URLField(blank=True, help_text='link da pesquisa', null=True)),
                ('pesq', models.ManyToManyField(through='sitenupeb.AutorRef', to='sitenupeb.AutoresPesq')),
            ],
        ),
        migrations.AddField(
            model_name='autorref',
            name='pesquisa',
            field=models.ForeignKey(help_text='pesquisa que o autor participa', null=True, on_delete=django.db.models.deletion.CASCADE, to='sitenupeb.RefereciaCita'),
        ),
        migrations.AddField(
            model_name='autorref',
            name='pesquisador',
            field=models.ForeignKey(help_text='pesquisadores que participam da pesquisa', null=True, on_delete=django.db.models.deletion.CASCADE, to='sitenupeb.AutoresPesq'),
        ),
    ]
