# Generated by Django 2.1.2 on 2018-11-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0055_auto_20181110_2039'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='autorespesq',
            options={'verbose_name': 'Autores Pesquisa', 'verbose_name_plural': 'Autores Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='autorref',
            options={'verbose_name': 'Autor Pesquisa', 'verbose_name_plural': 'Autor Pesquisa'},
        ),
        migrations.AlterModelOptions(
            name='refereciacita',
            options={'verbose_name': 'Referência bibliográfica', 'verbose_name_plural': 'Referências bibliográficas'},
        ),
        migrations.AddField(
            model_name='autorespesq',
            name='pesquisa',
            field=models.ForeignKey(blank=True, help_text='pesquisa que o autor participa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisaDoAutor', to='sitenupeb.RefereciaCita'),
        ),
        migrations.AlterField(
            model_name='autorref',
            name='pesquisa',
            field=models.ForeignKey(help_text='pesquisa que o autor participa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisarn', to='sitenupeb.RefereciaCita'),
        ),
        migrations.AlterField(
            model_name='autorref',
            name='pesquisador',
            field=models.ForeignKey(help_text='pesquisadores que participam da pesquisa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorDaPesquisa', to='sitenupeb.AutoresPesq'),
        ),
        migrations.AlterField(
            model_name='refereciacita',
            name='pesq',
            field=models.ManyToManyField(related_name='autoresDaPesquisa', through='sitenupeb.AutorRef', to='sitenupeb.AutoresPesq', verbose_name='pesquisador'),
        ),
        
      
    ]
