# Generated by Django 2.1.2 on 2018-11-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0056_auto_20181111_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorespesq',
            name='pesquisa',
        ),
        migrations.AddField(
            model_name='autorespesq',
            name='pesquisa',
            field=models.ManyToManyField(blank=True, help_text='pesquisa que o autor participa', null=True, related_name='pesquisaDoAutor', to='sitenupeb.RefereciaCita'),
        ),
    ]
