# Generated by Django 2.1.2 on 2018-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0057_auto_20181111_1606'),
    ]

    operations = [
        
       
        
    ]
