# Generated by Django 2.1.2 on 2018-11-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0058_auto_20181111_1636'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='autorespesq',
            name='pesquisa',
        ),
        
    ]
