# Generated by Django 2.1.2 on 2018-11-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0059_auto_20181111_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorespesq',
            name='pesquisa',
            field=models.ManyToManyField(help_text='pesquisa que o autor participa', related_name='pesquisaDoAutor', through='sitenupeb.AutorRef', to='sitenupeb.RefereciaCita', verbose_name='pesquisador'),
        ),
        migrations.AlterField(
            model_name='ppge',
            name='areadeconcentracao',
            field=models.CharField(blank=True, help_text='área de concentração', max_length=100, null=True, verbose_name='Área de concentração'),
        ),
    ]
