# Generated by Django 2.1.2 on 2018-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0060_auto_20181111_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinedebate',
            name='proximoFilme',
            field=models.ImageField(blank=True, help_text='logo do próximo filme', null=True, upload_to='imagens-cinedebate'),
        ),
    ]
