# Generated by Django 2.1.2 on 2018-11-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenupeb', '0061_cinedebate_proximofilme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proximofilme',
            options={'verbose_name': 'Próximo Filme', 'verbose_name_plural': 'Próximo Filme'},
        ),
        migrations.RemoveField(
            model_name='cinedebate',
            name='proximoFilme',
        ),
        migrations.AddField(
            model_name='proximofilme',
            name='proximoFilme',
            field=models.ImageField(blank=True, help_text='logo do próximo filme', null=True, upload_to='imagens-cinedebate'),
        ),
    ]
